import type { Metadata } from "next";
import Link from "next/link";
import {
  LEGAL_CONTACT_EMAILS,
  TERMS_AND_CONDITIONS_EFFECTIVE_DATE,
} from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms & Conditions | Dapto",
  description: "Terms & Conditions for the Dapto mobile and web application.",
};

const sections: Array<{
  title: string;
  paragraphs?: string[];
  bullets?: string[];
}> = [
  {
    title: "1. Nature of the Platform",
    paragraphs: [
      'Dapto (VISPL) is a technology platform that facilitates healthcare-related workflow tools and administrative services. Dapto (VISPL) is not a hospital, clinic, medical practice, healthcare provider, pharmacy, diagnostic center, or insurance provider.',
      "Medical consultations, diagnoses, prescriptions, and treatments are solely provided by licensed healthcare professionals using the platform.",
    ],
    bullets: [
      "Appointment scheduling and management",
      "Patient record management",
      "Prescription record storage and access",
      "Communication between authorized users",
      "Queue and clinic workflow management",
      "Related healthcare administrative services",
    ],
  },
  {
    title: "2. User Eligibility",
    paragraphs: [
      "You must be legally capable of entering into a binding agreement under applicable laws.",
      "If you create an account on behalf of a clinic, hospital, organization, or another individual, you represent that you are authorized to do so.",
    ],
  },
  {
    title: "3. Account Registration",
    paragraphs: ["You are responsible for all activities conducted through your account."],
    bullets: [
      "Provide accurate, complete, and current information.",
      "Maintain the confidentiality of your account credentials.",
      "Promptly update any information that becomes inaccurate.",
    ],
  },
  {
    title: "4. Appointments and Scheduling",
    paragraphs: [
      "Dapto (VISPL) facilitates appointment booking between users and healthcare professionals.",
      "Appointment availability is determined by the respective doctor, clinic, or healthcare provider.",
      "Doctors and clinics may reschedule, delay, or cancel appointments due to operational or medical reasons.",
    ],
    bullets: [
      "Appointment availability",
      "Appointment confirmation",
      "Consultation outcomes",
      "Waiting times",
      "Doctor availability",
    ],
  },
  {
    title: "5. Medical Services Disclaimer",
    paragraphs: [
      "Dapto (VISPL) does not provide medical advice, diagnosis, treatment, emergency care, or any other related healthcare services.",
      "All medical opinions, diagnoses, prescriptions, treatment plans, and healthcare decisions are solely the responsibility of the treating healthcare professional.",
      "Users should seek immediate emergency medical assistance by contacting emergency services or visiting the nearest healthcare facility in urgent situations.",
      "Dapto (VISPL) is not responsible for medical decisions, treatment outcomes, complications, injuries, losses, or damages arising from healthcare services provided through or outside the platform.",
    ],
  },
  {
    title: "6. Prescription and Medical Records",
    paragraphs: [
      "The platform may allow creation, storage, viewing, downloading, and sharing of prescription records and medical information.",
      "Doctors remain solely responsible for the content, accuracy, legality, and medical appropriateness of prescriptions and medical records generated through Dapto (VISPL).",
      "Users are responsible for reviewing their records and informing healthcare providers of any inaccuracies.",
      "Dapto (VISPL) does not independently verify medical information uploaded or generated by users.",
    ],
  },
  {
    title: "7. User Content",
    paragraphs: [
      "Users may upload information, documents, images, prescriptions, reports, and communications.",
      "Dapto (VISPL) may remove content that violates these Terms or applicable laws.",
    ],
    bullets: [
      "You own or are authorized to share such information.",
      "The information does not violate any law or third-party rights.",
      "The information is not false, misleading, fraudulent, or harmful.",
    ],
  },
  {
    title: "8. Communication Services",
    paragraphs: [
      "Dapto (VISPL) may provide messaging, notifications, reminders, and communication tools.",
      "We reserve the right to restrict or terminate access for misuse.",
    ],
    bullets: [
      "Send unlawful or abusive content.",
      "Harass or threaten others.",
      "Share misleading medical information.",
      "Engage in spam or fraudulent activity.",
    ],
  },
  {
    title: "9. Privacy",
    paragraphs: [
      "Your use of Dapto (VISPL) is also governed by our Privacy Policy.",
      "By using Dapto (VISPL), you consent to the collection, storage, processing, sharing, and use of information as described in the Privacy Policy.",
    ],
  },
  {
    title: "10. Data Security and Analytics",
    paragraphs: [
      "We implement reasonable security measures to protect information. However, no electronic system is completely secure.",
      "While we strive to protect data, we cannot guarantee absolute security and shall not be liable for unauthorized access, cyberattacks, system failures, or events beyond our reasonable control.",
      "Users acknowledge and agree that Dapto (VISPL) may collect, process, analyze, use, and share user data, including aggregated, anonymized, or de-identified information, for analytics, research, service improvement, operational insights, reporting, performance monitoring, business intelligence, platform enhancement, and forecasting or prediction purposes, in accordance with applicable laws and our Privacy Policy.",
    ],
  },
  {
    title: "11. Intellectual Property",
    paragraphs: [
      'All rights, title, and interest in Dapto (VISPL), including software, logos, designs, trademarks, content, and technology, remain the exclusive property of Vinfocom IT Services Private Limited ("VISPL") or its licensors.',
      "No ownership rights are transferred to users.",
    ],
  },
  {
    title: "12. Prohibited Activities",
    bullets: [
      "Reverse engineer the application.",
      "Attempt unauthorized access to systems.",
      "Interfere with platform functionality.",
      "Use automated tools to extract data.",
      "Upload malicious code.",
      "Impersonate another individual or organization.",
    ],
  },
  {
    title: "13. Suspension and Termination",
    paragraphs: ["We may suspend, restrict, or terminate access to Dapto (VISPL) at any time if:"],
    bullets: [
      "These Terms are violated.",
      "Fraudulent or suspicious activity is detected.",
      "Required by law.",
      "Necessary for security or operational reasons.",
    ],
  },
  {
    title: "14. Limitation of Liability",
    paragraphs: [
      "To the maximum extent permitted by law, Dapto (VISPL), Vinfocom IT Services Private Limited (VISPL), its directors, employees, affiliates, contractors, and partners shall not be liable for the following. Use of the platform is at your own risk.",
    ],
    bullets: [
      "Medical outcomes or treatment decisions.",
      "Appointment cancellations or delays.",
      "Errors in user-provided information.",
      "Data loss or service interruptions.",
      "Indirect, incidental, consequential, special, or punitive damages.",
    ],
  },
  {
    title: "15. Third-Party Services",
    paragraphs: [
      "Dapto (VISPL) may integrate with third-party services such as cloud providers, notification services, analytics tools, communication service providers, payment providers, or healthcare systems.",
      "Such services are governed by their own terms and policies.",
    ],
  },
  {
    title: "16. Modifications to Services",
    paragraphs: ["We may modify, suspend, discontinue, or update any part of Dapto (VISPL) without prior notice."],
  },
  {
    title: "17. Changes to Terms",
    paragraphs: [
      "We may update these Terms from time to time.",
      "Continued use of Dapto (VISPL) after changes become effective constitutes acceptance of the revised Terms.",
    ],
  },
  {
    title: "18. Governing Law and Jurisdiction",
    paragraphs: [
      "These Terms shall be governed by the laws of India.",
      "Any dispute arising from these Terms shall be subject to the exclusive jurisdiction of the courts located in Delhi, India.",
    ],
  },
  {
    title: "19. Account Deletion and Data Requests",
    paragraphs: [
      "Users may request account deletion by contacting us.",
      "Following verification, eligible data will be deleted within a reasonable period, subject to legal, regulatory, audit, security, medical record retention, compliance requirements, and legitimate business purposes including analytics records maintained in anonymized or aggregated form where permitted by law.",
    ],
  },
];

export default function TermsAndConditionsPage() {
  return (
    <main className="min-h-screen bg-gray-50 px-4 py-10">
      <div className="mx-auto max-w-4xl rounded-2xl border border-gray-200 bg-white p-6 md:p-10">
        <h1 className="text-3xl font-bold text-gray-900">Terms &amp; Conditions</h1>
        <p className="mt-2 text-sm text-gray-600">
          Effective Date: {TERMS_AND_CONDITIONS_EFFECTIVE_DATE}
        </p>
        <p className="mt-6 text-gray-700 leading-7">
          Welcome to Dapto (VISPL), a healthcare appointment, clinic management, and
          patient record platform operated by Vinfocom IT Services Private Limited
          ("VISPL", "Dapto (VISPL)", "we", "our", or "us").
        </p>
        <p className="mt-4 text-gray-700 leading-7">
          By creating an account, accessing, or using Dapto (VISPL), you agree to be
          bound by these Terms &amp; Conditions ("Terms"). If you do not agree with these
          Terms, please do not use the application.
        </p>

        {sections.map((section) => (
          <section key={section.title} className="mt-8 space-y-3">
            <h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
            {section.paragraphs?.map((paragraph) => (
              <p key={paragraph} className="text-gray-700 leading-7">
                {paragraph}
              </p>
            ))}
            {section.bullets?.length ? (
              <ul className="list-disc space-y-2 pl-6 text-gray-700 leading-7">
                {section.bullets.map((bullet) => (
                  <li key={bullet}>{bullet}</li>
                ))}
              </ul>
            ) : null}
          </section>
        ))}

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">20. Contact Us</h2>
          <p className="text-gray-700 leading-7">For questions regarding these Terms, please contact:</p>
          <ul className="list-disc space-y-2 pl-6 text-gray-700 leading-7">
            {LEGAL_CONTACT_EMAILS.map((email) => (
              <li key={email}>
                <a className="font-medium text-indigo-600 hover:text-indigo-700" href={`mailto:${email}`}>
                  {email}
                </a>
              </li>
            ))}
          </ul>
          <p className="text-gray-700 leading-7">
            Dapto (VISPL)
            <br />
            Vinfocom IT Services Private Limited (VISPL)
          </p>
          <p className="text-gray-700 leading-7">
            You can also review our{" "}
            <Link href="/privacy-policy" className="font-medium text-indigo-600 hover:text-indigo-700">
              Privacy Policy
            </Link>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
